services:
  site:
    build:
      context: .
    environment:
      BUILD_DIR: /build/site
    volumes:
      - ./:/opt/app
      - build:/build

  web_server:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - site

volumes:
  build: