#!/bin/bash
BUILD_DIR="/var/www/blog"
TARGET="/home/derek/blog"
GIT_DIR="/home/derek/blog.git"
BRANCH="master"

while read oldrev newrev ref
do
	# only checking out the master (or whatever branch you would like to deploy)
	if [[ $ref = refs/heads/$BRANCH ]];
	then
		echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
		git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f
		cd $TARGET
		npm run install
		export BUILD_DIR=$BUILD_DIR
		npm run build
	else
		echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
	fi
done
